# Site settings
title:          Nafees' Devlog
description:    "Nafees' Devlog"
url:            "https://nafeesb.github.io"

# Google Analytics
google_analytics: UA-153531604-1

# Author
author:
  name:         Nafees Bin Zafar
  url:          https://www.nafees.net
  email:        nb@nafees.net

# Build settings
markdown:       kramdown
highlighter: rouge
include:
  - _pages

collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec, vendor, scripts, _publications/template.md ]

# Disqus (Set to your disqus id)
disqus:         nafeesb
